# Generated by Django 5.1.2 on 2024-10-17 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_remove_usuario_rol_remove_usuario_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnoproyecto',
            name='alumno',
            field=models.CharField(max_length=255),
        ),
    ]
