# Generated by Django 5.1.2 on 2024-10-17 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0003_alter_alumnoproyecto_alumno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyectointegrador',
            name='anio',
        ),
    ]
