# Generated by Django 5.1.2 on 2024-10-31 03:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0004_remove_proyectointegrador_anio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('seccion', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='alumnoproyecto',
            name='alumno',
        ),
        migrations.RemoveField(
            model_name='alumnoproyecto',
            name='fecha_descarga',
        ),
        migrations.RemoveField(
            model_name='proyectointegrador',
            name='profesor',
        ),
        migrations.AddField(
            model_name='alumnoproyecto',
            name='alumno_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='proyectointegrador',
            name='documento_pdf',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='proyectointegrador',
            name='imagen',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='alumnoproyecto',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyectos.proyectointegrador'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='fecha_comentario',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyectos.proyectointegrador'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historialproyecto',
            name='descripcion',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='historialproyecto',
            name='fecha_actualizacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historialproyecto',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyectos.proyectointegrador'),
        ),
        migrations.AlterField(
            model_name='historialproyecto',
            name='titulo',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='historialproyecto',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='proyectointegrador',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyectos.categoriaproyecto'),
        ),
        migrations.AlterField(
            model_name='proyectointegrador',
            name='fecha_presentacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alumnoproyecto',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyectos.grupo'),
        ),
        migrations.CreateModel(
            name='Valoracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estrellas', models.IntegerField(default=0)),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyectos.proyectointegrador')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Documento',
        ),
    ]
