# Generated by Django 5.1.2 on 2024-10-31 03:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0005_grupo_remove_alumnoproyecto_alumno_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnoproyecto',
            name='alumno_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='alumnoproyecto',
            name='grupo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='proyectos.grupo'),
        ),
        migrations.AlterField(
            model_name='alumnoproyecto',
            name='proyecto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='proyectos.proyectointegrador'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='fecha_comentario',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='proyecto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='proyectos.proyectointegrador'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historialproyecto',
            name='fecha_actualizacion',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='historialproyecto',
            name='proyecto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='proyectos.proyectointegrador'),
        ),
        migrations.AlterField(
            model_name='proyectointegrador',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='proyectos.categoriaproyecto'),
        ),
        migrations.AlterField(
            model_name='proyectointegrador',
            name='fecha_presentacion',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='valoracion',
            name='proyecto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='proyectos.proyectointegrador'),
        ),
        migrations.AlterField(
            model_name='valoracion',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
