# Generated by Django 5.1.2 on 2024-10-31 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0007_alter_alumnoproyecto_alumno_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnoproyecto',
            name='alumno_id',
            field=models.IntegerField(default=1),
        ),
    ]
