# Generated by Django 5.1.2 on 2024-10-31 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0008_alter_alumnoproyecto_alumno_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyectointegrador',
            name='documento_pdf',
        ),
        migrations.AddField(
            model_name='proyectointegrador',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to='documentos/'),
        ),
        migrations.AlterField(
            model_name='proyectointegrador',
            name='fecha_presentacion',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='proyectointegrador',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/'),
        ),
        migrations.AlterField(
            model_name='proyectointegrador',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
