# Generated by Django 5.1.2 on 2024-10-31 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0011_seccion_remove_grupo_seccion_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='alumnoproyecto',
            unique_together={('proyecto', 'grupo')},
        ),
        migrations.AddField(
            model_name='alumnoproyecto',
            name='seccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyectos.seccion'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='seccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyectos.seccion'),
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyectos.grupo')),
                ('seccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyectos.seccion')),
            ],
        ),
        migrations.RemoveField(
            model_name='alumnoproyecto',
            name='alumno_id',
        ),
    ]
