# Generated by Django 5.1.2 on 2024-10-31 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0012_alter_alumnoproyecto_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyectointegrador',
            name='fecha_presentacion',
        ),
        migrations.AddField(
            model_name='proyectointegrador',
            name='año',
            field=models.IntegerField(default=2024),
        ),
    ]
