# Generated by Django 5.1.2 on 2024-11-01 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0014_proyectointegrador_semestre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyectointegrador',
            name='semestre',
        ),
        migrations.CreateModel(
            name='Año',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.IntegerField(default=2024)),
                ('semestre', models.IntegerField(choices=[(1, '1'), (2, '2')], default=1)),
            ],
            options={
                'unique_together': {('año', 'semestre')},
            },
        ),
        migrations.AddField(
            model_name='alumnoproyecto',
            name='año',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyectos.año'),
        ),
        migrations.AlterField(
            model_name='proyectointegrador',
            name='año',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyectos.año'),
        ),
    ]
