# Generated by Django 5.1.2 on 2024-11-01 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0015_remove_proyectointegrador_semestre_año_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectointegrador',
            name='url_github',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='proyectointegrador',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
