# Generated by Django 5.1.3 on 2024-11-07 14:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0017_alumno_año'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valoracion',
            name='estrellas',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
